### ISSUE TITLE
Generation quality is so low compared to native OA model.

### ISSUE THREAD

**Issue by HCBlackFox** [NolanoOrg/cformers#24]
I think something is wrong with the quantisation script?

**Comment by Ayushk4** [comment]
I will have a look at it today.

**Comment by HCBlackFox** [comment]
> I will have a look at it today.

Thank you

**Comment by Ayushk4** [comment]
This should have been fixed in #26

**Comment by HCBlackFox** [comment]
> This should have been fixed in #26

Yes, now works very well!

**Comment by Ayushk4** [comment]
Thanks.
