### ISSUE TITLE
Upload Open-Chat-Kit models at int4 on huggingface and add the URL mapping to interface.py

### ISSUE THREAD

**Issue by Ayushk4** [NolanoOrg/cformers#27]
Since GPT-NeoX support (Pythia based Open Assistant models) has been confirmed by #24 , we can port other chat-models.

Instructions:
- Port to GGML Format: `python3 cformers/cpp/converters/convert_gptneox_to_ggml.py <MODEL_CARD> <SAVE_PATH> 1`
- Quantize `cd cformers/cpp && make` , `./quantize SAVE_PATH QUANTIZE_SAVE_PATH 2`
- Upload to huggingface, update `cformers/interface.py` with path and update README

**Comment by HCBlackFox** [comment]
I will help with that today.

**Comment by HCBlackFox** [comment]
I`m on the finall stage, uploading to the HF.

**Comment by HCBlackFox** [comment]
https://huggingface.co/Black-Engineer/OpenChatKit_q4/tree/main

**Comment by tejasvaidhyadev** [comment]
Thanks.

**Comment by Ayushk4** [comment]
Thanks, a lot!
